# Generated by Django 6.0.5 on 2026-07-01 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_question_worksheet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyllabusSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("GCSE", "GCSE"),
                            ("A-Level", "A-Level"),
                            ("KS3", "KS3"),
                            ("Primary", "Primary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SyllabusModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("topics", models.TextField(help_text="Comma separated topics")),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="website.syllabussubject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PastPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board",
                    models.CharField(
                        choices=[
                            ("AQA", "AQA"),
                            ("Edexcel", "Edexcel"),
                            ("OCR", "OCR"),
                        ],
                        max_length=50,
                    ),
                ),
                ("year", models.IntegerField()),
                ("paper_name", models.CharField(max_length=200)),
                ("link", models.URLField()),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="past_papers",
                        to="website.syllabussubject",
                    ),
                ),
            ],
        ),
    ]
